---
- name: 'Provision Image'
  hosts: default
  become: true
  vars:
    packages: [postgresql15]

  tasks:
    - name: "Install {{ packages }}"
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ packages }}"
